export const PATH = {
  BIKE_HISTORY: "/bike-history",
  BIKE_HISTORY_SEARCH: "search",
  BIKE_HISTORY_DETAIL: "detail",
  BIKE_HISTORY_COMPONENT_INFO: "component-info",
  POST_BUNDLE: "/post-bundle",
  POST_BUNDLE_CASE: "/post-bundle-case",
  OVERVIEW: "overview",
  VERIFY_CODE: "verify-code",
  BRAND_CHECK: "brand-check",
  VERIFY_BIKE: "verify-bike",
  TEAM_MEMBERS: "/team-members",
  INVITE_DEALER: "invite-dealer",
  SEND_EMAIL_SUCCESS: "send-email-success",
  LOGIN: "/login",
  ERROR_PAGE: "/404",
  NO_PERMISSION: "/no-permission",
  FORGET_PASSWORD: "/forget-password",
  RESET_PASSWORD: "/reset-password",
  CHANGE_PASSWORD: "/change-password",
  CHANGE_TEMP_PASSWORD: "/change-temp-password",
  BIKE_AUTHORIZATION: "/bike-authorization",
  BIKE_AUTHORIZATION_DETAIL: "detail",
}
